const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
const ALL_PRODUCT1_REQUEST = "ALL_PRODUCT_REQUEST";
const ALL_PRODUCT_2REQUEST = "ALL_PRODUCT_REQUEST";
const ALL_PRODUCT_R3EQUEST = "ALL_PRODUCT_REQUEST";